### ISSUE TITLE
Predicting the class of unseen images

### ISSUE THREAD

**Issue by AnushaMehta** [gabrielpierobon/cnnshapes#1]
Hello, 
I am using jpg images of bicycles and bikes. Image size is 256x256. There are two classes: bicycle and bike. The number of training and testing images are 70 and 30 respectively.

`img_path = 'test_set/bike/20190129-214707-248962.jpg'
img = image.load_img(img_path)
img_tensor = image.img_to_array(img)
img_tensor = np.expand_dims(img_tensor, axis=0)
img_tensor /= 255.
plt.imshow(img_tensor[0])
plt.show()
print(img_tensor.shape)`

After executing this code, I am getting error as follows:
`AttributeError: 'numpy.ndarray' object has no attribute 'load_img'`

I have tried it with argument target_size also but same error generates. Can anyone tell me, how to solve this?

**Comment by AnushaMehta** [comment]
> Hello,
> I am using jpg images of bicycles and bikes. Image size is 256x256. There are two classes: bicycle and bike. The number of training and testing images are 70 and 30 respectively.
> 
> `img_path = 'test_set/bike/20190129-214707-248962.jpg' img = image.load_img(img_path) img_tensor = image.img_to_array(img) img_tensor = np.expand_dims(img_tensor, axis=0) img_tensor /= 255. plt.imshow(img_tensor[0]) plt.show() print(img_tensor.shape)`
> 
> After executing this code, I am getting error as follows:
> `AttributeError: 'numpy.ndarray' object has no attribute 'load_img'`
> 
> I have tried it with argument target_size also but same error generates. Can anyone tell me, how to solve this?

> Hello,
> I am using jpg images of bicycles and bikes. Image size is 256x256. There are two classes: bicycle and bike. The number of training and testing images are 70 and 30 respectively.
> 
> `img_path = 'test_set/bike/20190129-214707-248962.jpg' img = image.load_img(img_path) img_tensor = image.img_to_array(img) img_tensor = np.expand_dims(img_tensor, axis=0) img_tensor /= 255. plt.imshow(img_tensor[0]) plt.show() print(img_tensor.shape)`
> 
> After executing this code, I am getting error as follows:
> `AttributeError: 'numpy.ndarray' object has no attribute 'load_img'`
> 
> I have tried it with argument target_size also but same error generates. Can anyone tell me, how to solve this?

Sorry. It was a silly mistake. Importing : from keras.preprocessing import image, I do solve it.

**Comment by TuulaP** [comment]
stumbled to same, but needed to add a bit more for python 3.7. , but this issue got me to right track, so thanks !

`img = tf.compat.v1.keras.preprocessing.image.load_img( ... ) `

plus, to get all the layer images stored : 

`plt.savefig('foo_{0}'.format(layer_name) + ".png")  `

**Comment by soans1994** [comment]
hello, 

Is the class activation nothing but the intermediate output features of each layer? how is it different from Gradcam visualization

thank you
